os: linux
dist: focal
group: edge
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - aria2
      - wget
      - zstd
      - xz-utils

services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "droid8wars" --password-stdin 2>/dev/null
before_script:
  - cd $HOME && mkdir vdf200-firmware
  # Download the TWRP Compressed Source Files from PhantomZone54's Release
  # > More on https://github.com/PhantomZone54/twrp_sources_norepo/releases/latest
  # If Building for Oreo-based Devices
  - TWRP_SOURCE1="https://www.mediafire.com/file/xjy4ajg1a6u8vp2/Vodafone_VFD200_SPD_7731_SE2_20160927.zip/file"
  # Then uncomment below lines to download & extract the multi-part files
  - cd $HOME/vdf200-firmware/
  - wget 'https://www.mediafire.com/file/xjy4ajg1a6u8vp2/Vodafone_VFD200_SPD_7731_SE2_20160927.zip/file'  # Optional: You might need to switch from https://transfer.sh to https://file.io
  # - curl -s --upload-file TWRP-$version-${_CODENAME_}-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  provider: releases
  # The secret api_key will be loaded from the environment variables
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/vdf200-firmware/*.zip
  on:
    tags: true # Set "true" to deploy only on successful tagged commit builds
    repo: ${_USERNAME_}/${_REPO_SLUG_} # Optional: If you want to deploy on different repository
    branch: master # Optional: Needs to be exact as the config branch
branches:
  only:
    - master # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
